name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

  aws-config:
    runs-on: ubuntu-latest

    steps:
      - name: Configuring AWS credentials
        uses: ./.github/workflows/configure_aws_credentials.yml
        with:
          aws_region: us-east-1
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}

  terraform:
    runs-on: ubuntu-latest
    needs: aws-config

    steps:
      - name: Installing Terraform
        uses: ./.github/workflows/provide_infrastructure.yml
        with:
          aws_region: us-east-1
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
