name: AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

  configure-credentials:
    name: AWS Credentials
    runs-on: ubuntu-latest
    needs:
      - checkout

    steps:
      - name: Configure AWS Credentials
        uses:  aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

  install-terraform:
    name: Installing Terraform
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials

    steps:
      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v3

  init-terraform:
    name: Terraform
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials
      - install-terraform

    steps:
      - name: AWS Credentials to Terraform
        run: |
          echo Creating environment variables
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_SESSION_TOKEN=${{secrets.AWS_SESSION_TOKEN}}

      - name: Checkout Terraform Files
        uses: actions/checkout@v4

      - name: Terraform Initializing
        run: terraform init

      - name: Terraform Planning
        run: terraform plan -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ env.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ env.aws_secret_access_key }}
          AWS_SESSION_TOKEN: ${{ env.aws_session_token }}

      - name: Terraform Applying
        run: terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ env.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ env.aws_secret_access_key }}
          AWS_SESSION_TOKEN: ${{ env.aws_session_token }}