name: AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

  configure-credentials:
    name: AWS Credentials
    runs-on: ubuntu-latest
    needs:
      - checkout

    steps:
      - name: Configure AWS Credentials
        uses:  aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

  install-terraform:
    name: Installing Terraform
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials

    steps:
      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v3

  configure-credentials-to-environment:
    name: Configuring Environment Vars
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials
      - install-terraform

    steps:
      - name: Configuring Secrets to Environment
        run: echo Configuring Secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  init-terraform:
    name: Terraform Init
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials
      - install-terraform
      - configure-credentials-to-environment

    steps:
      - name: Checkout Terraform Files
        uses: actions/checkout@v4

      - name: Terraform Initializing
        run: terraform init

  plan-terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials
      - install-terraform
      - configure-credentials-to-environment
      - init-terraform

    steps:
      - name: Checkout Terraform Files
        uses: actions/checkout@v4

      - name: Terraform Planning
        run: terraform plan -out=tfplan

  apply-terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials
      - install-terraform
      - configure-credentials-to-environment
      - init-terraform
      - plan-terraform

    steps:
      - name: Checkout Terraform Files
        uses: actions/checkout@v4

      - name: Terraform Applying
        run: terraform apply --auto-approve