name: AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  provide-infrastructure:
    name: Create Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses:  aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::427107249392:role/LabRole
          aws-region: us-east-1

      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configuring Secrets to Environment
        run: echo Configuring Secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Initializing
        run: terraform init

      - name: Terraform Planning
        run: terraform plan -out=tfplan

      - name: Terraform Applying
        run: terraform apply --auto-approve