name: AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

  configure-credentials:
    name: AWS Credentials
    runs-on: ubuntu-latest
    needs:
      - checkout

    steps:
      - name: Configure AWS Credentials
        uses:  aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

  install-terraform:
    name: Installing Terraform
    runs-on: ubuntu-latest
    needs:
      - checkout
      - configure-credentials

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
        run: |
          export AWS_ACCESS_KEY_ID="$env:AWS_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY="$env:AWS_SECRET_ACCESS_KEY"
          export AWS_SESSION_TOKEN="$env:AWS_SESSION_TOKEN"
          
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_SESSION_TOKEN

      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Initializing
        run: terraform init

      - name: Terraform Planning
        run: terraform plan -out=tfplan

      - name: Terraform Applying
        run: terraform apply --auto-approve